export type FallbackCourse = {
  id: number;
  title: string;
  description: string;
  level: 'beginner' | 'intermediate' | 'advanced';
  categoryId: number;
  imageUrl?: string;
  duration: number;
  lessonCount: number;
  rating: number;
  reviewCount: number;
  isPublished: boolean;
  price: number;
  isFree: boolean;
};

export const fallbackCourses: FallbackCourse[] = [
  {
    id: 1,
    title: 'Kiswahili 101: Greetings & Introductions',
    description: 'Learn to greet, introduce yourself, and be polite in Kiswahili.',
    level: 'beginner',
    categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?w=1200',
    duration: 60,
    lessonCount: 3,
    rating: 4.8,
    reviewCount: 25,
    isPublished: true,
    price: 0,
    isFree: true,
  },
  {
    id: 2,
    title: 'Daily Conversation: Common Phrases',
    description: 'Build confidence with everyday phrases and responses.',
    level: 'beginner',
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1529070538774-1843cb3265df?w=1200',
    duration: 75,
    lessonCount: 4,
    rating: 4.7,
    reviewCount: 18,
    isPublished: true,
    price: 10,
    isFree: false,
  },
  {
    id: 3,
    title: 'Travel Kiswahili: Getting Around',
    description: 'Essential phrases for transport, directions, and accommodation.',
    level: 'beginner',
    categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cec?w=1200',
    duration: 90,
    lessonCount: 5,
    rating: 4.6,
    reviewCount: 12,
    isPublished: true,
    price: 15,
    isFree: false,
  },
  {
    id: 4,
    title: 'Kiswahili Pronunciation Mastery',
    description: 'Master vowel harmony and consonant sounds with drills.',
    level: 'beginner',
    categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1559619403-432e05df86f8?w=1200',
    duration: 45,
    lessonCount: 3,
    rating: 4.5,
    reviewCount: 9,
    isPublished: true,
    price: 0,
    isFree: true,
  },
  {
    id: 5,
    title: 'Food & Market Kiswahili',
    description: 'Order food, bargain at markets, and discuss ingredients.',
    level: 'intermediate',
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=1200',
    duration: 80,
    lessonCount: 5,
    rating: 4.7,
    reviewCount: 21,
    isPublished: true,
    price: 12,
    isFree: false,
  },
  {
    id: 6,
    title: 'Directions & Transportation',
    description: 'Ask for and give directions, taxis, buses, and ridesharing.',
    level: 'intermediate',
    categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1529070538774-1843cb3265df?w=1200',
    duration: 70,
    lessonCount: 4,
    rating: 4.6,
    reviewCount: 14,
    isPublished: true,
    price: 10,
    isFree: false,
  },
  {
    id: 7,
    title: 'Storytelling & Narratives',
    description: 'Craft compelling short stories and testimonies in Kiswahili.',
    level: 'intermediate',
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1462524500090-89443873e2b4?w=1200',
    duration: 85,
    lessonCount: 5,
    rating: 4.8,
    reviewCount: 19,
    isPublished: true,
    price: 14,
    isFree: false,
  },
  {
    id: 8,
    title: 'Professional Kiswahili: Meetings & Emails',
    description: 'Use polite registers and structure formal communication.',
    level: 'advanced',
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200',
    duration: 120,
    lessonCount: 6,
    rating: 4.8,
    reviewCount: 11,
    isPublished: true,
    price: 25,
    isFree: false,
  },
  {
    id: 9,
    title: 'Culture & Idioms',
    description: 'Understand cultural context and common idiomatic expressions.',
    level: 'advanced',
    categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1499364615650-ec38552f4f34?w=1200',
    duration: 95,
    lessonCount: 5,
    rating: 4.9,
    reviewCount: 33,
    isPublished: true,
    price: 20,
    isFree: false,
  },
  {
    id: 10,
    title: 'Media Kiswahili: Current Affairs',
    description: 'Analyze news, podcasts, and debates with advanced vocabulary.',
    level: 'advanced',
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200',
    duration: 110,
    lessonCount: 6,
    rating: 4.9,
    reviewCount: 27,
    isPublished: true,
    price: 28,
    isFree: false,
  },
];


