export type FallbackCourse = {
  id: number;
  title: string;
  description: string;
  level: 'beginner' | 'intermediate' | 'advanced';
  categoryId: number;
  imageUrl?: string;
  duration: number;
  lessonCount: number;
  rating: number;
  reviewCount: number;
  isPublished: boolean;
  price: number;
  isFree: boolean;
};

export const fallbackCourses: FallbackCourse[] = [
  {
    id: 1,
    title: 'Stewardship Foundations',
    description: 'Learn the biblical mindset for budgeting, giving, and goal setting.',
    level: 'beginner',
    categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200',
    duration: 60,
    lessonCount: 3,
    rating: 4.9,
    reviewCount: 42,
    isPublished: true,
    price: 0,
    isFree: true,
  },
  {
    id: 2,
    title: 'Debt Detox Sprint',
    description: 'Build a grace-filled debt elimination plan with practical checkpoints.',
    level: 'beginner',
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200',
    duration: 75,
    lessonCount: 4,
    rating: 4.7,
    reviewCount: 31,
    isPublished: true,
    price: 15,
    isFree: false,
  },
  {
    id: 3,
    title: 'Family Budget Workshop',
    description: 'Create shared budgets, money meetings, and savings rhythms for the whole household.',
    level: 'beginner',
    categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200',
    duration: 90,
    lessonCount: 5,
    rating: 4.8,
    reviewCount: 28,
    isPublished: true,
    price: 19,
    isFree: false,
  },
  {
    id: 4,
    title: 'Generosity Playbook',
    description: 'Design a giving strategy that aligns with your calling and cash flow.',
    level: 'beginner',
    categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200',
    duration: 50,
    lessonCount: 3,
    rating: 4.6,
    reviewCount: 22,
    isPublished: true,
    price: 0,
    isFree: true,
  },
  {
    id: 5,
    title: 'Marketplace Leaders Intensive',
    description: 'Lead team finances with integrity, forecasting tools, and stewardship dashboards.',
    level: 'intermediate',
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?w=1200',
    duration: 95,
    lessonCount: 5,
    rating: 4.9,
    reviewCount: 37,
    isPublished: true,
    price: 29,
    isFree: false,
  },
  {
    id: 6,
    title: 'Financial Coaching Essentials',
    description: 'Learn the frameworks, questions, and tools behind effective faith-based coaching.',
    level: 'intermediate',
    categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200',
    duration: 80,
    lessonCount: 4,
    rating: 4.7,
    reviewCount: 24,
    isPublished: true,
    price: 22,
    isFree: false,
  },
  {
    id: 7,
    title: 'Kingdom Investing Basics',
    description: 'Explore values-driven portfolios, risk, and long-term planning rooted in Scripture.',
    level: 'intermediate',
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=1200',
    duration: 85,
    lessonCount: 5,
    rating: 4.8,
    reviewCount: 26,
    isPublished: true,
    price: 24,
    isFree: false,
  },
  {
    id: 8,
    title: 'Church Finance Operations',
    description: 'Establish policies, reporting rhythms, and board-ready dashboards for ministries.',
    level: 'advanced',
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200',
    duration: 120,
    lessonCount: 6,
    rating: 4.9,
    reviewCount: 18,
    isPublished: true,
    price: 35,
    isFree: false,
  },
  {
    id: 9,
    title: 'Legacy & Estate Planning',
    description: 'Craft legacy letters, trusts, and charitable strategies with confidence.',
    level: 'advanced',
    categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1200',
    duration: 90,
    lessonCount: 5,
    rating: 4.8,
    reviewCount: 21,
    isPublished: true,
    price: 32,
    isFree: false,
  },
  {
    id: 10,
    title: 'Global Missions Fundraising Lab',
    description: 'Design campaigns, partner updates, and reporting systems for missionaries.',
    level: 'advanced',
    categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200',
    duration: 110,
    lessonCount: 6,
    rating: 4.9,
    reviewCount: 29,
    isPublished: true,
    price: 30,
    isFree: false,
  },
];


